### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Euro-pol** [GILLESMaster/Grilensto-Sniper#1]
just found ur github, remember the cookie empire or smth like that discord :sob: :fire:

**Comment by GILLESMaster** [comment]
I do!

I made a new server tho, and moved away from selling account cookies

**Comment by Euro-pol** [comment]
oh nice. i also moved on from beaming :sob:

**Comment by GILLESMaster** [comment]
You still have my discord @Euro-pol 
If not, just contact me, it's in my repo, id like to talk to you again!

**Comment by Euro-pol** [comment]
i got terminated like 4 while we didnt talk but sure i'll be happy to talk again lol
